name: auto_mappr_annotation
description: Annotations for the auto_mappr code-generator of mapping between objects with ease.
version: 1.1.0
repository: https://github.com/netglade/auto_mappr
issue_tracker: https://github.com/netglade/auto_mappr/issues

environment:
  sdk: ">=2.18.7 <4.0.0"

dev_dependencies:
  netglade_analysis: ^2.0.0-rc.1
  test: ^1.16.0
