name: auto_mappr_annotation
resolution: workspace
description: Annotations for the auto_mappr code-generator of mapping between objects with ease.
version: 2.3.0
repository: https://github.com/netglade/auto_mappr
issue_tracker: https://github.com/netglade/auto_mappr/issues

environment:
  sdk: ^3.9.0

dev_dependencies:
  netglade_analysis: ^19.0.0
  test: ^1.25.0
