name: auto_mappr_annotation
description: Annotations for the auto_mappr code-generator of mapping between objects with ease.
version: 1.42.0
repository: https://github.com/netglade/auto_mappr
issue_tracker: https://github.com/netglade/auto_mappr/issues

environment:
  sdk: ^3.0.0

dev_dependencies:
  netglade_analysis: ^4.2.0
  test: ^1.16.0
