name: auto_mappr_example
description: Example project how to use AutoMappr
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  auto_mappr_annotation: ^2.0.0
  equatable: ^2.0.5

dev_dependencies:
  auto_mappr: ^2.0.0
  build_runner: ^2.0.0
  netglade_analysis: ^8.0.0
  test: ^1.16.0
