name: auto_mappr_annotation_example
description: Example project
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.7 <4.0.0"

dependencies:
  auto_mappr_annotation:
    path: ../

dev_dependencies:
  build_runner: ^2.0.0
  netglade_analysis: ^4.0.0
  test: ^1.16.0
