name: auto_mappr_annotation_example
description: Example project
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  auto_mappr_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  netglade_analysis: ^9.0.0
  test: ^1.16.0
