name: examples_drift
description: Example project with AutoMappr and Drift integration
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.7 <3.0.0"

dependencies:
  auto_mappr_annotation: ^1.1.0
  drift: ^2.7.0
  equatable: ^2.0.5

dev_dependencies:
  auto_mappr: ^1.3.0
  build_runner: ^2.0.0
  drift_dev: ^2.7.0
  netglade_analysis: ^2.0.0
  test: ^1.16.0
