name: examples_drift
description: Example project with AutoMappr and Drift integration
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  auto_mappr_annotation: ^2.3.0
  drift: ^2.24.0
  equatable: ^2.0.7

dev_dependencies:
  auto_mappr: ^2.7.0
  build_runner: '>=2.0.0 <3.0.0'
  drift_dev: ^2.24.0
  netglade_analysis: ^15.0.0
  test: '>=1.25.0 <2.0.0'

