name: examples_freezed
description: Example project with AutoMappr and Freezed integration
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.7 <4.0.0"

dependencies:
  auto_mappr_annotation: ^2.0.0
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0

dev_dependencies:
  auto_mappr: ^2.0.0
  build_runner: ^2.0.0
  freezed: ^2.3.2
  netglade_analysis: ^6.0.0
  test: ^1.16.0
