name: examples_json_serializable
description: Example project with AutoMappr and JsonSerializable
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  auto_mappr_annotation: ^2.3.0
  json_annotation: ^4.9.0

dev_dependencies:
  auto_mappr: ^2.6.0
  build_runner: ^2.0.0
  json_serializable: ^6.6.1
  netglade_analysis: ^15.0.0
  test: '>=1.25.0 <2.0.0'

