name: examples_json_serializable
description: Example project with AutoMappr and JsonSerializable
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.7 <3.0.0"

dependencies:
  auto_mappr_annotation: ^1.1.0
  json_annotation: ^4.8.0

dev_dependencies:
  auto_mappr: ^1.3.0
  build_runner: ^2.0.0
  json_serializable: ^6.6.1
  netglade_analysis: ^2.0.0
  test: ^1.16.0
