name: examples_injectable
description: Example project how to use AutoMappr with Injectable
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.7 <4.0.0"

dependencies:
  auto_mappr_annotation: ^1.2.0
  equatable: ^2.0.5
  get_it: ^7.3.0
  injectable: ^2.1.1

dev_dependencies:
  auto_mappr: ^1.6.0
  build_runner: ^2.0.0
  injectable_generator: ^2.1.5
  netglade_analysis: ^4.2.0
  test: ^1.16.0
